# Generated by Django 6.0.1 on 2026-01-17 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='연도')),
                ('department_name', models.CharField(max_length=100, verbose_name='부서명')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='예산 총액')),
                ('is_approved', models.BooleanField(default=False, verbose_name='승인 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '연간 예산',
                'verbose_name_plural': '연간 예산 목록',
            },
        ),
        migrations.CreateModel(
            name='BudgetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='지출 일자')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='금액')),
                ('description', models.TextField(verbose_name='지출 내용')),
                ('vendor', models.CharField(blank=True, max_length=100, verbose_name='거래처')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='영수증')),
                ('status', models.CharField(choices=[('pending', '승인 대기'), ('approved', '승인됨'), ('rejected', '반려됨')], default='pending', max_length=20, verbose_name='결재 상태')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='결재 일시')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='반려 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL, verbose_name='결재자')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budget.annualbudget', verbose_name='관련 예산')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='신청자')),
            ],
            options={
                'verbose_name': '지출 내역',
                'verbose_name_plural': '지출 내역 목록',
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='거래일자')),
                ('transaction_type', models.CharField(choices=[('income', '수입'), ('expense', '지출')], max_length=10, verbose_name='구분')),
                ('description', models.CharField(max_length=200, verbose_name='적요')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='금액')),
                ('category', models.CharField(blank=True, help_text='예: 헌금, 사례비, 시설비 등', max_length=50, verbose_name='분류')),
                ('payer_receiver', models.CharField(blank=True, max_length=100, verbose_name='수입/지출처')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '현금거래',
                'verbose_name_plural': '현금출납부',
                'ordering': ['transaction_date', 'id'],
            },
        ),
    ]
