# Generated by Django 6.0.1 on 2026-01-11 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='헌금유형')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='코드')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '헌금유형',
                'verbose_name_plural': '헌금유형 관리',
            },
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='금액')),
                ('offering_date', models.DateField(verbose_name='헌금일자')),
                ('worship_date', models.DateField(blank=True, null=True, verbose_name='예배일자')),
                ('payment_method', models.CharField(choices=[('cash', '현금'), ('transfer', '계좌이체'), ('card', '카드'), ('check', '수표')], default='cash', max_length=20, verbose_name='결제방법')),
                ('bank_name', models.CharField(blank=True, max_length=50, verbose_name='은행명')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='계좌번호')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='참조번호')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='확인여부')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='members.churchmember', verbose_name='헌금자')),
                ('offering_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='offerings.offeringtype', verbose_name='헌금유형')),
            ],
            options={
                'verbose_name': '헌금',
                'verbose_name_plural': '헌금 관리',
                'ordering': ['-offering_date', '-id'],
            },
        ),
    ]
