# Generated by Django 6.0.1 on 2026-01-15 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_churchmember_member_id'),
        ('offerings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCertificateIssueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='증명서 연도')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='발급일시')),
                ('issue_type', models.CharField(choices=[('html', 'HTML 조회'), ('pdf', 'PDF 다운로드'), ('print', '인쇄')], default='html', max_length=20, verbose_name='발급유형')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='발급자')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_logs', to='members.churchmember', verbose_name='교인')),
            ],
            options={
                'verbose_name': '증명서 발급 로그',
                'verbose_name_plural': '증명서 발급 로그',
                'ordering': ['-issued_at'],
            },
        ),
    ]
