# Generated by Django 6.0.1 on 2026-01-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=20, unique=True, verbose_name='교인번호')),
                ('korean_name', models.CharField(max_length=50, verbose_name='한글이름')),
                ('english_name', models.CharField(blank=True, max_length=50, verbose_name='영문이름')),
                ('gender', models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성')], max_length=1, verbose_name='성별')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('baptism_date', models.DateField(blank=True, null=True, verbose_name='세례일')),
                ('family_id', models.CharField(blank=True, max_length=20, verbose_name='가족번호')),
                ('relationship', models.CharField(blank=True, max_length=20, verbose_name='가족관계')),
                ('phone', models.CharField(max_length=20, verbose_name='휴대전화')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('department', models.CharField(blank=True, max_length=50, verbose_name='부서')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='직분')),
                ('status', models.CharField(choices=[('active', '등록교인'), ('inactive', '비활성'), ('visitor', '새신자')], default='active', max_length=20, verbose_name='상태')),
                ('offering_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='헌금봉투번호')),
                ('tax_issuance_consent', models.BooleanField(default=False, verbose_name='세금공제동의')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
            ],
            options={
                'verbose_name': '교인',
                'verbose_name_plural': '교인 관리',
                'ordering': ['korean_name'],
            },
        ),
    ]
