# Generated by Django 6.0.1 on 2026-01-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchmember',
            name='member_id',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='교인번호'),
        ),
    ]
